version: '3.8'

services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    image: gateway-service:latest
    ports:
      - '3000:3000'
    env_file:
      - ./gateway-service/.env
    depends_on:
      - auth-service
      - user-service
      - blog-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - '4000:4000'

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest
    ports:
      - '4001:4001'

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    image: blog-service:latest
    ports:
      - '4002:4002'
